---
apiVersion: v1
kind: Pod
metadata:
  name: basicpod
  labels:
    type: webserver  
  type: NodePort    
spec:
  containers:
    - name: webcont
      image: nginx
      ports:
        - containerPort: 80
